spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springcloud?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: productservice
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
server:
  port: 8082
logging:
  level:
    springcloud.test.order.web.mapper.MallProductMapper: trace  
mybatis:
  type-aliases-package: springcloud.test.product.web.model
  mapper-locations: classpath:mapping/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
 